### ISSUE TITLE
请问能否修改为爬取png原图？

### ISSUE THREAD

**Issue by Ruinedmynight** [mokeyjay/Yandere-crawler#10]
首先感谢作者大大的付出，其次现脚本爬取的为jpg格式，看代码属实找不到在哪里修改，图片不够清晰，请问能否升级一下子改成爬取png大图呢？万分感谢

**Comment by Vepnore** [comment]
能否提供一个出现问题的例子？
当前版本的代码中包含限制下载图片尺寸的功能，但不包含超出限制时降级下载的功能，因此一个下载任务只对应三个结果：跳过、下载png原图、下载jpg大图。默认尺寸限制为15M，可以通过将配置文件中的`file_size_limit`置0禁用限制。
事实上，截止至记录1062028，排除因各种原因而被删除的记录，网站上61.12%的图片都没有png格式的原图。

**Comment by Ruinedmynight** [comment]
好的，谢谢回复

**Comment by Ruinedmynight** [comment]
还有一个问题望解答，如何开启多线程下载以提升下载速度？

**Comment by Vepnore** [comment]
多线程用这个：
```
get_data(settings)
for task in [parallel_task(settings) for _ in range(threads)]:
    task.join()
```
（我假设你知道应该在哪里换）
当在物理内存不足且未开启虚拟内存的设备上运行或网络条件极佳时，建议仅使用单线程。前者可能爆内存，后者可能被临时禁IP。

**Comment by Ruinedmynight** [comment]
我看了下你的库，试着运行了一下，但是一直卡在正在读取第一页，等很久后出现重试，我不知道问题出在哪

**Comment by Ruinedmynight** [comment]
# 建立线程
    # 只启用了单线程
    get_data(settings, tags)
    parallel_task(settings, discard_tags).join()
是在这里替换吗？

**Comment by Vepnore** [comment]
> 是在这里替换吗？

是的。

> 我看了下你的库，试着运行了一下，但是一直卡在正在读取第一页，等很久后出现重试，我不知道问题出在哪

”我的库“？如果你指我的fork，那个是协程版本的，提交的几次更改是从这几年里累积修改的版本逆推回去的中间版本，不一定稳定。默认日志等级是`WARNING`，排查错误建议改成`INFO`或`DEBUG`。如果不需要文件日志可以把`logger.addHandler(fh)`注释掉。

协程版只有尚未提交的本地版本能保证稳定运行，因为懒得写更新日志所以没提交~反正没人问（但现在有了）~，提交后会合并到主分支。

**Comment by Ruinedmynight** [comment]
哈哈，谢谢回复
    get_data(settings, tags)
    for task in [parallel_task(settings, discard_tags) for _ in range(threads)]:
        task.join()
我改成这样报错Traceback (most recent call last):
  File "D:\Tool\Project\Yandere-crawler-master\index.py", line 286, in <module>
    main(settings, tags, discard_tags, '', True)
  File "D:\Tool\Project\Yandere-crawler-master\index.py", line 156, in main
    for task in [parallel_task(settings, discard_tags) for _ in range(threads)]:
                                                                ^^^^^^^^^^^^^^
TypeError: 'module' object cannot be interpreted as an integer
属实整不明白，无基础知识，百度完看了也很懵圈，等你更新了我再试试看吧，谢谢

**Comment by Vepnore** [comment]
`threads`是应当由你自行替换的变量，指定并行下载线程数，整型。
改个名再赋值或者直接换成数字都可以。

**Comment by Ruinedmynight** [comment]
好的，谢谢解答
