### ISSUE TITLE
能爬取特定画册吗

### ISSUE THREAD

**Issue by fivebaigei** [mokeyjay/Yandere-crawler#11]
如何通过yande某个画册的网址（如https://yande.re/pool/show/98459）爬取该画册中所有图片呢？

**Comment by Vepnore** [comment]
没做，但是[API doc](https://yande.re/help/api#pools)里有写。
按id请求pool内容的url是`https://yande.re/pool/show.json?id={pool_id}`，只多了一些pool特定的信息。
那我更一版吧。

**Comment by fivebaigei** [comment]
牛，确实可以了，谢谢大佬

**Comment by fivebaigei** [comment]
好的，感谢大佬
