### ISSUE TITLE
请问如何指定抓取页面的图呢

### ISSUE THREAD

**Issue by unppu** [mokeyjay/Yandere-crawler#15]
纯小白，还请大佬指点

**Comment by Vepnore** [comment]
按页抓取时，在`config.json`中把`start_page`和`stop_page`的**值**改成起始页码和终止页码，如果只下载一页而不是几页，把起始页码和终止页码设成**相同值**。
如果要抓取的页面**非常老**，可能还需要把`last_stop_id`的值设为0，如果**启用了tag搜索**，则应把`tagSearch_last_stop_id`设为0。
