### ISSUE TITLE
正在读取第1页…… 建立连接时发生异常: https://yande.re/post.json?page=1 Cannot connect to host yande.re:443 ssl:default [信号灯超时时间已到]，剩余重试次数10次。 为什么？

### ISSUE THREAD

**Issue by oQAQo** [mokeyjay/Yandere-crawler#17]
https://yande.re/post.json?page=1是可以访问的，我执行    async def get_page(self) -> list | None:         logging.warning(f"正在读取第{self.page}页……")         url = f"https://yande.re/post.json?tags={self.tags_str}&page={self.page}" if self.flag_tag_search else f"https://yande.re/post.json?page={self.page}"         return await self.get_data(url)代码的时候却出现：正在读取第1页…… 建立连接时发生异常: https://yande.re/post.json?page=1 Cannot connect to host yande.re:443 ssl:default [信号灯超时时间已到]，剩余重试次数10次。 为什么？

**Comment by Vepnore** [comment]
我没有遇到并且不知道如何复现你说的这个问题，你可能需要找找其他原因，比如有没有使用网络代理，代理是否支持或不支持某些特性。

**Comment by oQAQo** [comment]
找到问题了，代理问题。查了一堆资料，最后自己排除，是代理的问题，谢谢！

**Comment by Vepnore** [comment]
解决了就好，没有其他问题我就关闭issue了

**Comment by jiut** [comment]
https://github.com/mokeyjay/Yandere-crawler/blob/536cb7a6533fa2b9a0f68138909457dc98bdc76f/Http.py#L34

把这里的ssl验证关了就行。
https://www.bright.cn/blog/how-tos/proxy-in-aiohttp

`response = await session.get(url, ssl=False) if special_headers is None else await session.get(url, ssl=False, headers=special_headers.update(headers))`
